# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBAd1vG4feGAIk8fyzGC0srQBOqYDeP4
"""

from telegram_bot import start_bot

if __name__ == "__main__":
    start_bot()