# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BVxY8cE7cNehj2JkvbZFVWFhQb8k7BT
"""

class ProbSumModel:
    def __init__(self, base_model):
        self.model = base_model

    def predict_sum(self, X):
        probs = self.model.predict_proba(X)[:, 1]
        return probs.sum()