# -*- coding: utf-8 -*-
"""route_risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12E_6Z6sL-n0DyCY4DViaX7fDmS9zbutc
"""

import joblib
import os
import numpy as np
from model import ProbSumModel

# Загрузи модель один раз
model = joblib.load("model/model.pkl")

def predict_risk(route_coords, weather_row, period):
    """
    route_coords: список координат [(lat, lon), ...]
    weather_row: pd.Series с погодой
    period: строка "Следующие 3 ч" или "Следующие 24 ч"

    Возвращает: (risk: float, city_avg: float)
    """
    # 🔸 Например: считаем уникальные geohash по маршруту
    import pygeohash as pgh
    geo_set = sorted({pgh.encode(lat, lon, precision=5) for lat, lon in route_coords})

    # 🔸 Объединяем признаки
    features = weather_row.copy()
    features["GeoCount"] = len(geo_set)
    features["Period"] = 3 if "3" in period else 24

    # Приводим к DataFrame с одной строкой
    import pandas as pd
    X = pd.DataFrame([features])

    # 🔸 Предсказание
    prob = model.predict_proba(X)[0, 1]  # вероятность класса 1

    # 🔸 Среднее значение по городу (захардкожено пока)
    city_avg = 0.28  # можно заменить на реальное значение

    return prob, city_avg
