# -*- coding: utf-8 -*-
"""telegram_bot0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdI3nw8NLCmHfjUAFPvFU_5ukcgaEvkv
"""

import os, asyncio
from telegram import Update
from telegram.ext import (ApplicationBuilder,
                         ContextTypes,
                         CommandHandler,
                         MessageHandler,
                         ConversationHandler,
                         filters
                         )

START_PC = 0      # единственное состояние

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    await update.message.reply_text("📍 Send postal code of the start point")
    return START_PC

async def receive_start_pc(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    # пока просто печатаем в консоль, потом сохраним и пойдём дальше
    print("Start PC:", update.message.text)
    await update.message.reply_text("✅ Got it (дальнейшие шаги — позже)")
    return ConversationHandler.END

async def main():
    app = (
        ApplicationBuilder()
        .token(os.getenv("BOT_TOKEN"))   # BOT_TOKEN задашь в Render
        .build()
    )
    conv = ConversationHandler(
        entry_points=[CommandHandler("start", start)],
        states={START_PC: [MessageHandler(filters.TEXT & ~filters.COMMAND, receive_start_pc)]},
        fallbacks=[],
    )
    app.add_handler(conv)
    await app.run_polling()

if __name__ == "__main__":
    asyncio.run(main())
