# -*- coding: utf-8 -*-
"""telegram_bot0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdI3nw8NLCmHfjUAFPvFU_5ukcgaEvkv
"""

import os, asyncio
from telegram import Update
from telegram.ext import (ApplicationBuilder,
                         ContextTypes,
                         CommandHandler,
                         MessageHandler,
                         ConversationHandler,
                         filters
                         )

START_PC = 0      # единственное состояние

    '''
    await: Поскольку бот работает асинхронно (async def), отправка сообщения - это короутина. await «дожидается» её завершения, не блокируя весь бот.
    update: Объект, который библиотека python-telegram-bot передаёт вашему хендлеру (хендлер - это функция start в данном случае). В нём лежит всё, что пришло от Telegram: сообщение пользователя, данные о чате, о пользователе и т.д.
    .message: Атрибут update, содержащий объект Message — конкретное входящее сообщение от пользователя.
    .reply_text(...): Метод Message, который отправляет ответ на то же сообщение (бот автоматически вставит «reply-to»).
                  Если ответить не на что (например, команда /start в личном чате), библиотека просто пришлёт новое сообщение.
    "📍 Send postal code of the start point": Текст, который бот пошлёт пользователю. Эмодзи «📍» подчёркивает, что речь о локации.
    '''
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:    # update - то, что прислал юзер, context — «чем воспользоваться» и «где сложить данные», чтобы помнить их в следующих шагах.
    await update.message.reply_text("📍 Send postal code of the start point")
    return START_PC

async def receive_start_pc(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    # пока просто печатаем в консоль, потом сохраним и пойдём дальше
    print("Start PC:", update.message.text)
    await update.message.reply_text("✅ Got it (дальнейшие шаги — позже)")
    return ConversationHandler.END

async def main():
    app = (
        ApplicationBuilder()
        .token(os.getenv("BOT_TOKEN"))   # BOT_TOKEN задашь в Render
        .build()
    )
    conv = ConversationHandler(
        entry_points=[CommandHandler("start", start)],
        states={START_PC: [MessageHandler(filters.TEXT & ~filters.COMMAND, receive_start_pc)]},
        fallbacks=[],
    )
    app.add_handler(conv)
    await app.run_polling()

if __name__ == "__main__":
    asyncio.run(main())